.\" created for ior-decode-2 by Chris Waters, for Debian GNU/Linux
.\"
.TH IOR-DECODE-2 1 "23 March 2002" "Version 0.5.15"

.SH NAME
ior\-decode\-2 \- print human-readable info from IOR string

.SH SYNOPSIS
.HP
.BI ior\-decode\-2 " IOR"

.SH DESCRIPTION
An IOR string is a string of characters that defines an "InterOrb
Reference".  These strings are used to locate and identify remote
objects.  The \fBior\-decode\-2\fP program displays the information
encoded in the IOR string in a human\-readable format.  This is
primarily useful for debugging.

.SH OPTIONS
None.

.SH SEE ALSO
http://www.omg.org, http://orbit-resource.sourceforge.net

.SH AUTHOR
Copyright \(co  2001 Dick Porter <dick@acm.org> and Elliot Lee
<sopwith@redhat.com>

This manual was originally written for ior\-decode\-2 by Chris Waters
<xtifr@debian.org> for Debian GNU/Linux.
